import { describe, it, expect, vi, beforeEach } from 'vitest';
import { FileFallbackService } from '../../services/sandbox/FileFallbackService';
import { SandboxEnvironment } from '../../sandbox';
import { AppConfig } from '../../types';

describe('FileFallbackService', () => {
    let service: FileFallbackService;
    let sandbox: SandboxEnvironment;
    let config: AppConfig;

    beforeEach(() => {
        service = new FileFallbackService();
        sandbox = {
            writeFile: vi.fn(),
            runCommand: vi.fn(),
        } as unknown as SandboxEnvironment;
        config = {} as unknown as AppConfig;
    });

    it('should generate empty placeholder for requirements.txt', async () => {
        await service.generatePlaceholder(config, 'requirements.txt', sandbox);
        expect(sandbox.writeFile).toHaveBeenCalledWith('requirements.txt', '# Placeholder generated by CI-Fixer\n');
    });

    it('should identify stale reference in Dockerfile', async () => {
        const content = 'RUN pip install -r missing-reqs.txt\nCOPY . .\n';
        const isStale = await service.isReferenceStale(config, 'missing-reqs.txt', content);
        expect(isStale).toBe(true);
    });

    it('should suggest removal of stale reference from Dockerfile', async () => {
        const content = 'RUN pip install -r missing-reqs.txt\nCOPY . .\n';
        const updated = await service.proposeReferenceRemoval(config, 'missing-reqs.txt', content);
        expect(updated).toBe('COPY . .\n');
    });
});
